//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Core.Properties {
    using System;

    /// <summary>
    ///   A strongly typed resource class for looking up localized strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Core.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // Navigation & general UI
        public static string BtnReturn { get { return ResourceManager.GetString("BtnReturn", resourceCulture); } }
        public static string MsgWelcome { get { return ResourceManager.GetString("MsgWelcome", resourceCulture); } }

        // Main menu (Console)
        public static string MenuMainMenu { get { return ResourceManager.GetString("MenuMainMenu", resourceCulture); } }
        public static string MenuCreate { get { return ResourceManager.GetString("MenuCreate", resourceCulture); } }
        public static string MenuDelete { get { return ResourceManager.GetString("MenuDelete", resourceCulture); } }
        public static string MenuOptionExecute { get { return ResourceManager.GetString("MenuOptionExecute", resourceCulture); } }
        public static string MenuOptionModify { get { return ResourceManager.GetString("MenuOptionModify", resourceCulture); } }
        public static string MenuOptionSave { get { return ResourceManager.GetString("MenuOptionSave", resourceCulture); } }
        public static string MenuLaunch { get { return ResourceManager.GetString("MenuLaunch", resourceCulture); } }
        public static string MenuSaveLaunch { get { return ResourceManager.GetString("MenuSaveLaunch", resourceCulture); } }
        public static string MenuAucunTravail { get { return ResourceManager.GetString("MenuAucunTravail", resourceCulture); } }
        public static string MenuQuit { get { return ResourceManager.GetString("MenuQuit", resourceCulture); } }

        // Backup creation / deletion (Console)
        public static string CreateSave { get { return ResourceManager.GetString("CreateSave", resourceCulture); } }
        public static string CreateFinish { get { return ResourceManager.GetString("CreateFinish", resourceCulture); } }
        public static string DeleteSave { get { return ResourceManager.GetString("DeleteSave", resourceCulture); } }
        public static string FinishDelete { get { return ResourceManager.GetString("FinishDelete", resourceCulture); } }
        public static string NameSave { get { return ResourceManager.GetString("NameSave", resourceCulture); } }
        public static string SourcePath { get { return ResourceManager.GetString("SourcePath", resourceCulture); } }
        public static string DestPath { get { return ResourceManager.GetString("DestPath", resourceCulture); } }
        public static string TypeSave { get { return ResourceManager.GetString("TypeSave", resourceCulture); } }
        public static string SureToDelete { get { return ResourceManager.GetString("SureToDelete", resourceCulture); } }
        public static string EnterReturn { get { return ResourceManager.GetString("EnterReturn", resourceCulture); } }

        // Job execution
        public static string ExecuteJob { get { return ResourceManager.GetString("ExecuteJob", resourceCulture); } }
        public static string StatusExecutingBackups { get { return ResourceManager.GetString("StatusExecutingBackups", resourceCulture); } }

        // Validation / Errors
        public static string JobAlreadyExists { get { return ResourceManager.GetString("JobAlreadyExists", resourceCulture); } }
        public static string JobIndexNotFound { get { return ResourceManager.GetString("JobIndexNotFound", resourceCulture); } }
        public static string JobNameEmpty { get { return ResourceManager.GetString("JobNameEmpty", resourceCulture); } }
        public static string MaxJobsReached { get { return ResourceManager.GetString("MaxJobsReached", resourceCulture); } }
        public static string ErrorCreateJob { get { return ResourceManager.GetString("ErrorCreateJob", resourceCulture); } }
        public static string SourceDirectoryEmpty { get { return ResourceManager.GetString("SourceDirectoryEmpty", resourceCulture); } }
        public static string SourceDirectoryNotFound { get { return ResourceManager.GetString("SourceDirectoryNotFound", resourceCulture); } }
        public static string TargetDirectoryEmpty { get { return ResourceManager.GetString("TargetDirectoryEmpty", resourceCulture); } }
        public static string DirectoryNoExist { get { return ResourceManager.GetString("DirectoryNoExist", resourceCulture); } }
        public static string DifferentialBackupCreated { get { return ResourceManager.GetString("DifferentialBackupCreated", resourceCulture); } }
        public static string ConfigSaveError { get { return ResourceManager.GetString("ConfigSaveError", resourceCulture); } }

        // Settings (Console)
        public static string SettingsTitle { get { return ResourceManager.GetString("SettingsTitle", resourceCulture); } }
        public static string TitleLog { get { return ResourceManager.GetString("TitleLog", resourceCulture); } }
        public static string TitleLogFormat { get { return ResourceManager.GetString("TitleLogFormat", resourceCulture); } }
        public static string LogFormatDescription { get { return ResourceManager.GetString("LogFormatDescription", resourceCulture); } }

        // Language
        public static string LangEnglish { get { return ResourceManager.GetString("LangEnglish", resourceCulture); } }
        public static string LangFrench { get { return ResourceManager.GetString("LangFrench", resourceCulture); } }
        public static string LanguageChanged { get { return ResourceManager.GetString("LanguageChanged", resourceCulture); } }

        // GUI tabs
        public static string TabExecute { get { return ResourceManager.GetString("TabExecute", resourceCulture); } }
        public static string TabCreate { get { return ResourceManager.GetString("TabCreate", resourceCulture); } }
        public static string TabManage { get { return ResourceManager.GetString("TabManage", resourceCulture); } }
        public static string TabSettings { get { return ResourceManager.GetString("TabSettings", resourceCulture); } }

        // Execute section
        public static string ExecuteTitle { get { return ResourceManager.GetString("ExecuteTitle", resourceCulture); } }
        public static string ExecuteDescription { get { return ResourceManager.GetString("ExecuteDescription", resourceCulture); } }
        public static string BtnExecute { get { return ResourceManager.GetString("BtnExecute", resourceCulture); } }

        // Create section
        public static string CreateTitle { get { return ResourceManager.GetString("CreateTitle", resourceCulture); } }
        public static string JobName { get { return ResourceManager.GetString("JobName", resourceCulture); } }
        public static string SourceFolder { get { return ResourceManager.GetString("SourceFolder", resourceCulture); } }
        public static string DestinationFolder { get { return ResourceManager.GetString("DestinationFolder", resourceCulture); } }
        public static string BackupType { get { return ResourceManager.GetString("BackupType", resourceCulture); } }
        public static string BackupTypeFull { get { return ResourceManager.GetString("BackupTypeFull", resourceCulture); } }
        public static string BackupTypeDifferential { get { return ResourceManager.GetString("BackupTypeDifferential", resourceCulture); } }
        public static string BtnBrowse { get { return ResourceManager.GetString("BtnBrowse", resourceCulture); } }
        public static string BtnCreate { get { return ResourceManager.GetString("BtnCreate", resourceCulture); } }

        // Manage section
        public static string ManageTitle { get { return ResourceManager.GetString("ManageTitle", resourceCulture); } }
        public static string ManageDesc { get { return ResourceManager.GetString("ManageDesc", resourceCulture); } }
        public static string BtnViewDetails { get { return ResourceManager.GetString("BtnViewDetails", resourceCulture); } }
        public static string BtnModify { get { return ResourceManager.GetString("BtnModify", resourceCulture); } }
        public static string BtnDelete { get { return ResourceManager.GetString("BtnDelete", resourceCulture); } }

        // Settings section (GUI)
        public static string SettingsAppTitle { get { return ResourceManager.GetString("SettingsAppTitle", resourceCulture); } }
        public static string Version { get { return ResourceManager.GetString("Version", resourceCulture); } }
        public static string VersionLabel { get { return ResourceManager.GetString("VersionLabel", resourceCulture); } }
        public static string LogsPath { get { return ResourceManager.GetString("LogsPath", resourceCulture); } }
        public static string LogsPathLabel { get { return ResourceManager.GetString("LogsPathLabel", resourceCulture); } }
        public static string ConfigPath { get { return ResourceManager.GetString("ConfigPath", resourceCulture); } }
        public static string ConfigLabel { get { return ResourceManager.GetString("ConfigLabel", resourceCulture); } }
        public static string StateFile { get { return ResourceManager.GetString("StateFile", resourceCulture); } }
        public static string StateLabel { get { return ResourceManager.GetString("StateLabel", resourceCulture); } }
        public static string ConfigFile { get { return ResourceManager.GetString("ConfigFile", resourceCulture); } }
        public static string AppDescription { get { return ResourceManager.GetString("AppDescription", resourceCulture); } }

        // Settings sub-sections
        public static string LanguageSection { get { return ResourceManager.GetString("LanguageSection", resourceCulture); } }
        public static string LanguageInterface { get { return ResourceManager.GetString("LanguageInterface", resourceCulture); } }
        public static string LanguageChoose { get { return ResourceManager.GetString("LanguageChoose", resourceCulture); } }
        public static string AboutSection { get { return ResourceManager.GetString("AboutSection", resourceCulture); } }
        public static string NavPaths { get { return ResourceManager.GetString("NavPaths", resourceCulture); } }
        public static string NavSecurity { get { return ResourceManager.GetString("NavSecurity", resourceCulture); } }
        public static string NavMultiThreading { get { return ResourceManager.GetString("NavMultiThreading", resourceCulture); } }
        public static string NavLogging { get { return ResourceManager.GetString("NavLogging", resourceCulture); } }
        public static string SectionPaths { get { return ResourceManager.GetString("SectionPaths", resourceCulture); } }
        public static string SectionSecurity { get { return ResourceManager.GetString("SectionSecurity", resourceCulture); } }
        public static string SectionMultiThreading { get { return ResourceManager.GetString("SectionMultiThreading", resourceCulture); } }
        public static string SectionLogging { get { return ResourceManager.GetString("SectionLogging", resourceCulture); } }

        // Paths settings labels
        public static string LabelLogsFolder { get { return ResourceManager.GetString("LabelLogsFolder", resourceCulture); } }
        public static string LabelConfigFile { get { return ResourceManager.GetString("LabelConfigFile", resourceCulture); } }
        public static string LabelStateFile { get { return ResourceManager.GetString("LabelStateFile", resourceCulture); } }

        // Security settings labels
        public static string EncryptionKeyTitle { get { return ResourceManager.GetString("EncryptionKeyTitle", resourceCulture); } }
        public static string LabelEncryptionKey { get { return ResourceManager.GetString("LabelEncryptionKey", resourceCulture); } }
        public static string LabelExtensionsToEncrypt { get { return ResourceManager.GetString("LabelExtensionsToEncrypt", resourceCulture); } }
        public static string LabelBusinessProcess { get { return ResourceManager.GetString("LabelBusinessProcess", resourceCulture); } }
        public static string BusinessProcessDescription { get { return ResourceManager.GetString("BusinessProcessDescription", resourceCulture); } }

        // Multi-threading settings labels
        public static string LabelPriorityExtensions { get { return ResourceManager.GetString("LabelPriorityExtensions", resourceCulture); } }
        public static string PriorityExtensionsDescription { get { return ResourceManager.GetString("PriorityExtensionsDescription", resourceCulture); } }
        public static string LabelMaxSimultaneousJobs { get { return ResourceManager.GetString("LabelMaxSimultaneousJobs", resourceCulture); } }
        public static string MaxJobsRange { get { return ResourceManager.GetString("MaxJobsRange", resourceCulture); } }
        public static string LabelFileSizeThreshold { get { return ResourceManager.GetString("LabelFileSizeThreshold", resourceCulture); } }
        public static string FileSizeThresholdDescription { get { return ResourceManager.GetString("FileSizeThresholdDescription", resourceCulture); } }
        public static string Megabytes { get { return ResourceManager.GetString("Megabytes", resourceCulture); } }

        // Logging settings labels
        public static string LabelLogTarget { get { return ResourceManager.GetString("LabelLogTarget", resourceCulture); } }
        public static string LogTargetLocalOnly { get { return ResourceManager.GetString("LogTargetLocalOnly", resourceCulture); } }
        public static string LogTargetServerOnly { get { return ResourceManager.GetString("LogTargetServerOnly", resourceCulture); } }
        public static string LogTargetBoth { get { return ResourceManager.GetString("LogTargetBoth", resourceCulture); } }
        public static string LabelServerIp { get { return ResourceManager.GetString("LabelServerIp", resourceCulture); } }

        // General action buttons
        public static string BtnValidate { get { return ResourceManager.GetString("BtnValidate", resourceCulture); } }
        public static string BtnSaveSettings { get { return ResourceManager.GetString("BtnSaveSettings", resourceCulture); } }
        public static string BtnSave { get { return ResourceManager.GetString("BtnSave", resourceCulture); } }
        public static string BtnResume { get { return ResourceManager.GetString("BtnResume", resourceCulture); } }
        public static string BtnStop { get { return ResourceManager.GetString("BtnStop", resourceCulture); } }
        public static string BtnPause { get { return ResourceManager.GetString("BtnPause", resourceCulture); } }
        public static string BtnStopJob { get { return ResourceManager.GetString("BtnStopJob", resourceCulture); } }
        public static string BtnPauseAll { get { return ResourceManager.GetString("BtnPauseAll", resourceCulture); } }
        public static string BtnResumeAll { get { return ResourceManager.GetString("BtnResumeAll", resourceCulture); } }
        public static string BtnStopAll { get { return ResourceManager.GetString("BtnStopAll", resourceCulture); } }
        public static string BtnClose { get { return ResourceManager.GetString("BtnClose", resourceCulture); } }

        // Backup statuses
        public static string StatusReady { get { return ResourceManager.GetString("StatusReady", resourceCulture); } }
        public static string StatusBackupCompleted { get { return ResourceManager.GetString("StatusBackupCompleted", resourceCulture); } }
        public static string StatusBackupsCompleted { get { return ResourceManager.GetString("StatusBackupsCompleted", resourceCulture); } }
        public static string StatusBackupPaused { get { return ResourceManager.GetString("StatusBackupPaused", resourceCulture); } }
        public static string StatusBackupResumed { get { return ResourceManager.GetString("StatusBackupResumed", resourceCulture); } }
        public static string StatusBackupStopped { get { return ResourceManager.GetString("StatusBackupStopped", resourceCulture); } }
        public static string StatusInProgress { get { return ResourceManager.GetString("StatusInProgress", resourceCulture); } }
        public static string StatusPaused { get { return ResourceManager.GetString("StatusPaused", resourceCulture); } }
        public static string StatusCompleted { get { return ResourceManager.GetString("StatusCompleted", resourceCulture); } }
        public static string StatusError { get { return ResourceManager.GetString("StatusError", resourceCulture); } }
        public static string StatusStopped { get { return ResourceManager.GetString("StatusStopped", resourceCulture); } }
        public static string StatusWaiting { get { return ResourceManager.GetString("StatusWaiting", resourceCulture); } }
        public static string GlobalControl { get { return ResourceManager.GetString("GlobalControl", resourceCulture); } }

        // Current file
        public static string CurrentFile { get { return ResourceManager.GetString("CurrentFile", resourceCulture); } }

        // GUI messages
        public static string NoValidJobSelected { get { return ResourceManager.GetString("NoValidJobSelected", resourceCulture); } }
        public static string PleaseSelectPlanToDelete { get { return ResourceManager.GetString("PleaseSelectPlanToDelete", resourceCulture); } }
        public static string PleaseSelectPlanForDetails { get { return ResourceManager.GetString("PleaseSelectPlanForDetails", resourceCulture); } }
        public static string PleaseFillAllFields { get { return ResourceManager.GetString("PleaseFillAllFields", resourceCulture); } }
        public static string ErrorPrefix { get { return ResourceManager.GetString("ErrorPrefix", resourceCulture); } }
        public static string PlanCreatedSuccessfully { get { return ResourceManager.GetString("PlanCreatedSuccessfully", resourceCulture); } }
        public static string PlanDeleted { get { return ResourceManager.GetString("PlanDeleted", resourceCulture); } }
        public static string ErrorWhileDeleting { get { return ResourceManager.GetString("ErrorWhileDeleting", resourceCulture); } }
        public static string FilesText { get { return ResourceManager.GetString("FilesText", resourceCulture); } }
        public static string RemainingText { get { return ResourceManager.GetString("RemainingText", resourceCulture); } }

        // Plan details
        public static string DetailsTitle { get { return ResourceManager.GetString("DetailsTitle", resourceCulture); } }
        public static string BackupPlanDetails { get { return ResourceManager.GetString("BackupPlanDetails", resourceCulture); } }
        public static string LabelName { get { return ResourceManager.GetString("LabelName", resourceCulture); } }
        public static string LabelType { get { return ResourceManager.GetString("LabelType", resourceCulture); } }
        public static string LabelSourcePath { get { return ResourceManager.GetString("LabelSourcePath", resourceCulture); } }
        public static string LabelDestinationPath { get { return ResourceManager.GetString("LabelDestinationPath", resourceCulture); } }
        public static string FileLabel { get { return ResourceManager.GetString("FileLabel", resourceCulture); } }

        // Folder / file selection
        public static string SelectFolder { get { return ResourceManager.GetString("SelectFolder", resourceCulture); } }
        public static string SelectLogsFolder { get { return ResourceManager.GetString("SelectLogsFolder", resourceCulture); } }
        public static string ErrorCreatingFolder { get { return ResourceManager.GetString("ErrorCreatingFolder", resourceCulture); } }
        public static string LogsFolderConfigured { get { return ResourceManager.GetString("LogsFolderConfigured", resourceCulture); } }
        public static string SelectConfigFileLocation { get { return ResourceManager.GetString("SelectConfigFileLocation", resourceCulture); } }
        public static string ConfigFileConfigured { get { return ResourceManager.GetString("ConfigFileConfigured", resourceCulture); } }
        public static string SelectStateFileLocation { get { return ResourceManager.GetString("SelectStateFileLocation", resourceCulture); } }
        public static string StateFileConfigured { get { return ResourceManager.GetString("StateFileConfigured", resourceCulture); } }

        // Business process alerts
        public static string BusinessProcessAlert { get { return ResourceManager.GetString("BusinessProcessAlert", resourceCulture); } }

        // Backup counter (GUI)
        public static string JobsCountNone { get { return ResourceManager.GetString("JobsCountNone", resourceCulture); } }
        public static string JobsCountOne { get { return ResourceManager.GetString("JobsCountOne", resourceCulture); } }
        public static string JobsCountMany { get { return ResourceManager.GetString("JobsCountMany", resourceCulture); } }

        // Console menus
        public static string MenuChangeLang { get { return ResourceManager.GetString("MenuChangeLang", resourceCulture); } }
        public static string MenuConfigServerIp { get { return ResourceManager.GetString("MenuConfigServerIp", resourceCulture); } }
        public static string MenuLogTarget { get { return ResourceManager.GetString("MenuLogTarget", resourceCulture); } }
        public static string LogTargetMenuTitle { get { return ResourceManager.GetString("LogTargetMenuTitle", resourceCulture); } }
        public static string MenuNoItemAvailable { get { return ResourceManager.GetString("MenuNoItemAvailable", resourceCulture); } }

        // Server IP menu (Console)
        public static string ServerIpMenuTitle { get { return ResourceManager.GetString("ServerIpMenuTitle", resourceCulture); } }
        public static string ServerIpCurrent { get { return ResourceManager.GetString("ServerIpCurrent", resourceCulture); } }
        public static string ServerIpNewPrompt { get { return ResourceManager.GetString("ServerIpNewPrompt", resourceCulture); } }
        public static string ServerIpSaved { get { return ResourceManager.GetString("ServerIpSaved", resourceCulture); } }
        public static string ServerIpCancelled { get { return ResourceManager.GetString("ServerIpCancelled", resourceCulture); } }
        public static string LogTargetModified { get { return ResourceManager.GetString("LogTargetModified", resourceCulture); } }


        // Pagination
        public static string BtnPrevious { get { return ResourceManager.GetString("BtnPrevious", resourceCulture); } }
        public static string BtnNext { get { return ResourceManager.GetString("BtnNext", resourceCulture); } }
        public static string LabelPerPage { get { return ResourceManager.GetString("LabelPerPage", resourceCulture); } }
        public static string PageIndicator { get { return ResourceManager.GetString("PageIndicator", resourceCulture); } }
        public static string PageIndicatorFull { get { return ResourceManager.GetString("PageIndicatorFull", resourceCulture); } }

        // Status messages
        public static string StatusLogFormatChanged { get { return ResourceManager.GetString("StatusLogFormatChanged", resourceCulture); } }
        public static string StatusLogTargetChanged { get { return ResourceManager.GetString("StatusLogTargetChanged", resourceCulture); } }
        public static string StatusServerIpUpdated { get { return ResourceManager.GetString("StatusServerIpUpdated", resourceCulture); } }
        public static string StatusThreadingApplied { get { return ResourceManager.GetString("StatusThreadingApplied", resourceCulture); } }
        public static string ErrorMaxJobsRange { get { return ResourceManager.GetString("ErrorMaxJobsRange", resourceCulture); } }
        public static string ErrorFileSizeThresholdMin { get { return ResourceManager.GetString("ErrorFileSizeThresholdMin", resourceCulture); } }
    }
}
